/**
 * Developer mode: fixture people to test the full loop against without
 * needing a second human and a second browser.
 *
 * Everything here is scoped to the signed-in developer by the permission
 * layer, not by this UI. `dev-profiles` is `read: 'own'`, so another user
 * cannot see these fixtures even if they go looking, and `matches` marked
 * `synthetic` are hidden from the rest of the app when the toggle is off.
 *
 * Seeding is batched: each `devSeed` call creates ten fixtures, because fifty
 * record writes in one worker invocation would sit uncomfortably close to the
 * subrequest ceiling. The loop below is what makes that visible as progress.
 */

import { useState } from 'react'
import { Bot, Loader2, Sparkles, Trash2 } from 'lucide-react'
import { useToast } from '@/components/ui'
import { ActionError, callAction } from '../lib/hottake'
import { DEV_PROFILE_COUNT } from '../schemas/hottake-schemas'
import { useDevProfiles } from '../lib/use-hottake'
import { cn } from '../lib/utils'

interface SeedResult {
  seeded: number
  target: number
  done: boolean
}

export default function DevPanel({ devMode }: { devMode: boolean }) {
  const { fixtures } = useDevProfiles()
  const { error: toastError, success } = useToast()
  const [busy, setBusy] = useState<null | 'toggle' | 'seed' | 'reset'>(null)
  const [progress, setProgress] = useState(0)

  async function toggle() {
    setBusy('toggle')
    try {
      await callAction('setDevMode', { enabled: !devMode })
    } catch (err) {
      toastError(
        "Couldn't change developer mode",
        err instanceof ActionError ? err.message : 'Try again.',
      )
    } finally {
      setBusy(null)
    }
  }

  async function seed() {
    setBusy('seed')
    setProgress(fixtures.length)
    try {
      // Loop until the action reports it is done. Bounded so a server that
      // never advances can't spin here forever.
      for (let call = 0; call < 12; call++) {
        const result = await callAction<SeedResult>('devSeed', {})
        setProgress(result.seeded)
        if (result.done) break
      }
      const matched = await callAction<{ matched: number }>('devMatch', {})
      success(
        'Developer mode ready',
        `${DEV_PROFILE_COUNT} fixtures, ${matched.matched} of them already matched you.`,
      )
    } catch (err) {
      toastError('Seeding failed', err instanceof ActionError ? err.message : 'Try again.')
    } finally {
      setBusy(null)
    }
  }

  async function reset() {
    setBusy('reset')
    try {
      const result = await callAction<{ removedProfiles: number; removedMatches: number }>(
        'devReset',
        {},
      )
      setProgress(0)
      success(
        'Fixtures cleared',
        `Removed ${result.removedProfiles} profiles and ${result.removedMatches} conversations.`,
      )
    } catch (err) {
      toastError('Reset failed', err instanceof ActionError ? err.message : 'Try again.')
    } finally {
      setBusy(null)
    }
  }

  const seeded = busy === 'seed' ? progress : fixtures.length

  return (
    <section className="mt-8 w-full rounded-2xl border border-border bg-card/60 p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <h2 className="flex items-center gap-2 text-sm font-bold text-foreground">
            <Bot className="h-4 w-4 text-primary" aria-hidden />
            Developer mode
          </h2>
          <p className="mt-1.5 text-xs leading-relaxed text-muted-foreground">
            Adds {DEV_PROFILE_COUNT} fixture people only you can see, some of whom
            match you. Their replies are generated by Groq. Turn it off and the app
            shows real people only.
          </p>
        </div>

        <button
          role="switch"
          aria-checked={devMode}
          aria-label="Developer mode"
          data-testid="dev-mode-toggle"
          onClick={() => void toggle()}
          disabled={busy !== null}
          className={cn(
            'relative mt-0.5 h-7 w-12 shrink-0 rounded-full transition-colors disabled:opacity-50',
            devMode ? 'bg-primary' : 'bg-secondary',
          )}
        >
          <span
            className={cn(
              'absolute top-1 h-5 w-5 rounded-full bg-white transition-transform',
              devMode ? 'translate-x-6' : 'translate-x-1',
            )}
          />
        </button>
      </div>

      {devMode && (
        <div className="mt-5 space-y-3" data-testid="dev-controls">
          <div className="flex items-center justify-between text-xs">
            <span className="text-muted-foreground">Fixtures</span>
            <span className="font-mono text-foreground">
              {seeded} / {DEV_PROFILE_COUNT}
            </span>
          </div>
          <div className="h-1.5 overflow-hidden rounded-full bg-secondary">
            <div
              className="h-full rounded-full bg-primary transition-all duration-300"
              style={{ width: `${Math.min(100, (seeded / DEV_PROFILE_COUNT) * 100)}%` }}
            />
          </div>

          <div className="flex gap-2 pt-1">
            <button
              onClick={() => void seed()}
              disabled={busy !== null}
              data-testid="dev-seed"
              className="flex flex-1 items-center justify-center gap-2 rounded-full bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
            >
              {busy === 'seed' ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
              ) : (
                <Sparkles className="h-3.5 w-3.5" aria-hidden />
              )}
              {fixtures.length > 0 ? 'Re-match' : 'Generate people'}
            </button>

            <button
              onClick={() => void reset()}
              disabled={busy !== null || fixtures.length === 0}
              data-testid="dev-reset"
              className="flex items-center justify-center gap-2 rounded-full border border-border px-4 py-2.5 text-xs font-medium text-muted-foreground transition-colors hover:border-destructive/60 hover:text-destructive disabled:opacity-40"
            >
              {busy === 'reset' ? (
                <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden />
              ) : (
                <Trash2 className="h-3.5 w-3.5" aria-hidden />
              )}
              Clear
            </button>
          </div>
        </div>
      )}
    </section>
  )
}
